version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-lambda-dynamo-ninjin-v3"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-qpj0zdllxuu6"
s3_prefix = "sam-lambda-dynamo-ninjin-v3"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
